apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: sysshow-userservice-ports
  namespace: default
spec:
  httpPipeline:
    handlers: []
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"
  metrics:
    enabled: true
  secrets:
    scopes:
      - storeName: "*"
        defaultAcessPolicy:
          allowAccess: true
  mlt:
    enabled: false
  accessControl:
    defaultAction: "allow"
    trustDomain: "public"