# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  sysshow-userservice-ports:
    build:
      context: "C:\\_PERSONAL\\Projects\\SysShow\\SysShow-UserService"
      dockerfile: "UserService.Ports/Dockerfile.dev"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "userservice/userservice.ports:dev"
    ports:
    - "127.0.0.1:57003:57100"
    - "127.0.0.1:57203:57300"
    volumes:
    - "C:\\Users\\chris\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\_PERSONAL\\Projects\\SysShow\\SysShow-UserService\\UserService.Ports:/app:rw"
    - "C:\\_PERSONAL\\Projects\\SysShow\\SysShow-UserService:/src:rw"
    - "C:\\Users\\chris\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.3\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\chris\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\chris\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_2_26_14_59_58:/var/opt/rider-debugger:rw"
    working_dir: "/app"
