apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sysShowPubSub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: "amqp://rabbitmq:5672"
  - name: protocol
    value: amqp
  - name: hostname
    value: rabbitmq
  - name: username
    value: guest
  - name: password
    value: guest
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: "0"
  - name: concurrency
    value: parallel